config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "summaries#index"

  resources :users do
    resources :summaries
  end

  resources :summaries do
    resources :foods, :only => [:create, :new]
  end

  resources :summaries do
    resources :exercises, :only => [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :summary
  validates :workout, :presence => true
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :summary
  validates :name, :presence => true
end

app/models/summary.rb
class Summary < ActiveRecord::Base
  belongs_to :user
  has_many :foods
  has_many :exercises
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :summaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def new
    @summary = Summary.find(params[:summary_id])
    @exercise = Exercise.new
  end

  def create
    @summary = Summary.find(params[:summary_id])
    @exercise = @summary.exercises.create(exercise_params)
    @summary.total -= @exercise.calorie_burn
    @summary.save
    respond_to  do |format|
        format.html { redirect_to user_summary_path(current_user.id, @summary.id) }
        format.js
      end
  end

  private
  def exercise_params
    params.require(:exercise).permit(:workout, :calorie_burn, :summary_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def new
    @summary = Summary.find(params[:summary_id])
    @food = Food.new
  end

  def create
    @summary = Summary.find(params[:summary_id])
    @food = @summary.foods.create(food_params)
    @summary.total += @food.calorie_intake
    @summary.consumed += @food.calorie_intake
    @summary.save
    respond_to  do |format|
        format.html { redirect_to user_summary_path(current_user.id, @summary.id) }
        format.js
      end
  end

  private
  def food_params
    params.require(:food).permit(:name, :calorie_intake, :summary_id)
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def index
    @summary = Summary.new
  end

  def create
    @summary = Summary.where(date: params[:date], user_id: current_user.id).first
    if @summary.nil?
      @summary = Summary.create(:user_id => current_user.id, :date => params[:date])
      redirect_to user_summary_path(current_user.id, @summary.id)
    else
      redirect_to user_summary_path(current_user.id, @summary.id)
    end
  end

  def show
    @summary = Summary.find(params[:id])
    @foods = @summary.foods
    @exercises = @summary.exercises
    respond_to  do |format|
        format.html {  }
        format.js
      end
  end

  def edit
  end

  # private
  # def summary_params
  #   params.require(:summary).permit(:user_id, :date)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/exercises/_exercise.html.erb
<div class="">
  <%= exercise.workout %> <br>
  <%= exercise.calorie_burn %>
</div>

app/views/exercises/_exercise_form.html.erb
<%= form_for [@summary, @exercise], remote: true do |f| %>
  <%= f.label :workout %>
  <%= f.text_field :workout %>
  <%= f.label :calorie_burn %>
  <%= f.text_field :calorie_burn %>
  <%= f.submit %>
<% end %>

app/views/exercises/create.js.erb
$('#new_exercise').remove();
$('#burn-link').show();
$('#exercise-list').prepend('<%= j render(@exercise) %>');
$('#total').html('<%= j render(@summary) %>');

app/views/exercises/new.js.erb
$('#burn-link').hide().after('<%= j render "exercises/exercise_form" %>');

app/views/foods/_food.html.erb
<div class="">
  <%= food.name %> <br>
  <%= food.calorie_intake %>
</div>

app/views/foods/_food_form.html.erb
<%= form_for [@summary, @food], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calorie_intake %>
  <%= f.text_field :calorie_intake %>
  <%= f.submit %>
<% end %>

app/views/foods/create.js.erb
$('#new_food').remove();
$('#intake-link').show();
$('#food-list').prepend('<%= j render(@food) %>');
$('#total').html('<%= j render(@summary) %>');

app/views/foods/new.js.erb
$('#intake-link').hide().after('<%= j render "foods/food_form" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitnessTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
       <div class="nav-wrapper black">
         <a href="/" class="brand-logo">Fitness Tracker</a>
         <ul id="nav-mobile" class="right hide-on-med-and-down">

           <% if user_signed_in? %>
             <strong><%= current_user.email %></strong>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>

         </ul>
       </div>
     </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %><br>
                <%= link_to "View", user_summaries_path(current_user, :date => day), method: :post, class: "view-button" %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/summaries/_summary.html.erb
<h3>Net Calories
  <%= @summary.total %>
</h3>

app/views/summaries/edit.html.erb
<h1>Days#edit</h1>
<p>Find me in app/views/days/edit.html.erb</p>

app/views/summaries/index.html.erb
<%= month_calendar do |date| %>
  <%= date.to_formatted_s(:short) %>
<% end %>

app/views/summaries/new.html.erb
<h1>Days#new</h1>
<p>Find me in app/views/days/new.html.erb</p>

app/views/summaries/show.html.erb
<h1> <%= @summary.date.to_formatted_s(:short) %> </h1>

<div class="row">
  <div class="col s10 card" id="total">
    <%= render("summary", summary: @summary) %>
  </div>
  <div class="col s5">
    <h5>Calorie Intake</h5>
    <div class="card" id="intake-link">
      <%= link_to "Add Meal", new_summary_food_path(@summary), remote: true%>
      <div id="food-list">
        <% @foods.each do |food| %>
          <%= render("foods/food", food: food) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col s5">
    <div class="card" id="burn-link">
      <h5>Calories Burned</h5>
      <%= link_to "Add Exercise", new_summary_exercise_path(@summary), remote: true%>
      <div id="exercise-list">
        <% @exercises.each do |ex| %>
          <%= render("exercises/exercise", exercise: ex) %>
        <% end %>
    </div>
  </div>
</div>